### ISSUE TITLE
Poetry install fails

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#32]
After using the copier tool to create an Agent project, `poetry install` will fail. Below is the error message from the poetry logs:

```
➜ poetry install
Updating dependencies
Resolving dependencies... (4.5s)

Writing lock file

No dependencies to install or update

  ValueError

  /Users/boni407/platformDriver/volttron-platform-driver/platform_driver does not contain any element

  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/core/masonry/utils/package_include.py:60 in check_elements
      56│         return any(element.suffix == ".py" for element in self.elements)
      57│
      58│     def check_elements(self):  # type: () -> PackageInclude
      59│         if not self._elements:
    → 60│             raise ValueError(
      61│                 "{} does not contain any element".format(self._base / self._include)
      62│             )
      63│
      64│         root = self._elements[0]

```

I believe that copier requires a two-nested project to house the agent code. In our last feedback session from the team, we wanted to have a one-layer folder to house the agent code, which was addressed in this commit https://github.com/VOLTTRON/copier-poetry-volttron-agent/commit/4cb03ef63b1eae31e1adfd0cc5db312a19133a51, and subsequently merged in this PR:
https://github.com/VOLTTRON/copier-poetry-volttron-agent/pull/18/commits

It seems that copier needs to have a two-nested project in order for `poetry install` to successfully complete. This issue is similar to: https://github.com/python-poetry/poetry/issues/3682.

When I reverted this commit (see [working branch](https://github.com/VOLTTRON/copier-poetry-volttron-agent/tree/bugix/projectfolder/project)) and reran copier, `'poetry install` successfully completed. 

# Steps to reproduce the error:

* Run copier using the latest commit from the develop branch (```copier "https://github.com/VOLTTRON/copier-poetry-volttron-agent.git" . --vcs-ref 9530bba```)
* Run ```poetry install``

After running `poetry install`, you will see the following error log:

```
  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/core/masonry/utils/package_include.py:60 in check_elements
      56│         return any(element.suffix == ".py" for element in self.elements)
      57│
      58│     def check_elements(self):  # type: () -> PackageInclude
      59│         if not self._elements:
    → 60│             raise ValueError(
      61│                 "{} does not contain any element".format(self._base / self._include)
      62│             )
      63│
      64│         root = self._elements[0]

```

# Proposed solution:

Instead of using 'project_name/project_name', use 'src/project_name' for the structure of the template.

**Comment by bonicim** [comment]
Related to #33

**Comment by kefeimo** [comment]
Fixed by #39. #48,
Manually closed.

**Comment by bonicim** [comment]
After testing the latest from [develop](https://github.com/VOLTTRON/copier-poetry-volttron-agent/tree/6140b21f05fbdc032f9390645827d943f7112873), I noticed that we are still getting the same error after running`poetry install` despite the fix by #39. 

While #39 did put back the two nested structure to help avoid this problem, we still saw the installation error because the pyproject.toml was still making a reference to a directory that does not exist. In the 'packages' section of [pyproject.toml, we see the following](https://github.com/VOLTTRON/copier-poetry-volttron-agent/blob/6140b21f05fbdc032f9390645827d943f7112873/project/pyproject.toml.jinja#L11):

```
packages = [ { include = "[[ python_package_import_name ]]", from = "[[ python_package_distribution_name ]]" } ]
```

However, since we renamed the top level folder from  "[[ python_package_distribution_name ]]"  to the hardcoded value of "src", `poetry` will fail installation when trying to construct the 'packages' reference. Thus, the installation error is a 'poetry' issue and not a 'copier' issue.

In another project that uses this pattern of hardcoding 'src' as the top level directory, note [how the author changed the packages section](https://github.com/pawamoy/copier-poetry/blob/master/project/pyproject.toml.jinja#L15):

```
packages = [ { include = "[[ python_package_import_name ]]", from = "src" } ]
```


Thus, to resolve our installation, we should do the same and uipdate project/pyproject.toml to use 'src' as part of the packages definition.
